package com.lsp.domain.agent.model.valobj.harness;

public enum DrawioIssueType {
    EMPTY_OUTPUT,
    INVALID_JSON,
    MISSING_CONTENT,
    UNEXPECTED_OUTPUT_TYPE,
    INCOMPLETE_MXFILE,
    INVALID_XML,
    MISSING_DIAGRAM,
    MISSING_GRAPH_MODEL,
    MISSING_ROOT,
    MISSING_ROOT_CELL,
    DUPLICATE_ID,
    MISSING_GEOMETRY,
    MISSING_EDGE_SOURCE,
    MISSING_EDGE_TARGET,
    MISSING_EDGE_GEOMETRY,
    BROKEN_EDGE_REFERENCE,
    BAD_XML_ESCAPING,
    LAYOUT_OVERLAP
}
